version: "3"
services:
    backend:
        build: backend/
        command: python ./app.py
        ports:
            - 5000:5000
    
    frontend:
        build: frontend/
        command: npm run serve
        ports:
            - 8080:8080
        depends_on:
            - backend